version: '3'
services:

  ghost:
    image: ghost:alpine
    ports:
      - "80:2368"
    volumes:
      - /opt/ghost/content:/var/lib/ghost/content
    restart: always
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      url: "https://jefflazerus.com"

networks:
  default:
    external:
      name: mean_default
